apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ooblex.fullname" . }}-secrets
  labels:
    {{- include "ooblex.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  
  # RabbitMQ Credentials
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  
  # Redis Password
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  
  # JWT Secret
  JWT_SECRET: {{ .Values.security.secrets.jwt | quote }}
  
  # Grafana Credentials
  GRAFANA_USER: {{ .Values.grafana.adminUser | quote }}
  GRAFANA_PASSWORD: {{ .Values.grafana.adminPassword | quote }}