apiVersion: v1
kind: Secret
metadata:
  name: ooblex-secrets
  namespace: ooblex
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: "ooblex"
  POSTGRES_PASSWORD: "change-me-in-production"
  POSTGRES_DB: "ooblex"
  
  # RabbitMQ Credentials
  RABBITMQ_USER: "admin"
  RABBITMQ_PASS: "change-me-in-production"
  
  # JWT Secret
  JWT_SECRET: "your-secret-key-change-in-production"
  
  # Optional: Cloud Storage
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  
  # Optional: Monitoring
  SENTRY_DSN: ""
  GRAFANA_USER: "admin"
  GRAFANA_PASSWORD: "change-me-in-production"